# Generated by Django 4.2.1 on 2023-05-17 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_alter_item_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.EmailField(blank=True, max_length=254, verbose_name='Pożyczone dla (email)')),
                ('notes', models.TextField(blank=True, max_length=9000, verbose_name='Notatka')),
                ('priv_notes', models.TextField(blank=True, max_length=9000, verbose_name='Notatka prywatna')),
                ('proposal', models.BooleanField(verbose_name='Propozycja')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Dzień wypożyczenia')),
                ('date_stop', models.DateField(blank=True, verbose_name='Termin oddania')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pożyczone dla')),
            ],
        ),
    ]
