# Generated by Django 4.2.1 on 2023-05-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True, max_length=9000, verbose_name='Opis'),
        ),
    ]
