# Generated by Django 4.2.1 on 2023-05-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_public_alter_item_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Ogłoszenie publiczne'),
        ),
    ]
