# Generated by Django 4.2 on 2023-04-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='item',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
