# Generated by Django 4.2 on 2023-04-26 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0004_alter_user_options_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lender_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='imię')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nazwisko')),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('desc', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cauthor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
