# Generated by Django 4.2 on 2023-04-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0005_deal_lender_desc_alter_deal_lender_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktywny'),
        ),
    ]
